### ISSUE TITLE
Duplicate but not identical entries from Clarin Resources exist such as GATE, Nametag, UDPipe, Marian NMT

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/marketplace-curation#10]

**Comment by laureD19** [comment]
UDPipe 3 records merged. New one: https://marketplace.sshopencloud.eu/tool-or-service/i6piia

**Comment by laureD19** [comment]
NameTag 2 records merged. New one: https://marketplace.sshopencloud.eu/tool-or-service/UdeKHU

**Comment by laureD19** [comment]
For GATE, I suggest we keep [GATE Cloud](https://marketplace.sshopencloud.eu/tool-or-service/QaXwEt) and [GATE (General Architecture for Text Engineering)](https://marketplace.sshopencloud.eu/tool-or-service/gNhbSz) in the MP with a relation with the two. 

Ok for you @carikan @mkrzmr ? Or do you think we should have only item explaining the framework and the cloud/as-a-service approach?

**Comment by laureD19** [comment]
[Marian NMT](https://marketplace.sshopencloud.eu/tool-or-service/Mo4qsb) item created - didn't exist before and linked to three datasets using it, that were already in the MP. Let me know if you disagree with the approach

**Comment by carikan** [comment]
> For GATE, I suggest we keep [GATE Cloud](https://marketplace.sshopencloud.eu/tool-or-service/QaXwEt) and [GATE (General Architecture for Text Engineering)](https://marketplace.sshopencloud.eu/tool-or-service/gNhbSz) in the MP with a relation with the two.
> 
> Ok for you [@carikan](https://github.com/carikan) [@mkrzmr](https://github.com/mkrzmr) ? Or do you think we should have only item explaining the framework and the cloud/as-a-service approach?

Thank you! I think we should keep them seperate with a relation.
