### ISSUE TITLE
Curate tools without description

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/marketplace-curation#11]
Some tools have "no description provided" as description text. This is probably from ingest, but should be curated.

List of items: 

https://docs.google.com/spreadsheets/d/1DS5TULJ6z6WPfYZ_LA9cK7vWFO3CWn5mI-qWyHuqRME/edit?usp=sharing

**Comment by carikan** [comment]
Added descriptions. Need to discuss more during the curation meeting.

**Comment by carikan** [comment]
Added another sheet into the same file for publications without description.

**Comment by laureD19** [comment]
I can take care of the delete cases

**Comment by mkrzmr** [comment]
@mkrzmr also find the tools with very long description

**Comment by mkrzmr** [comment]
Here are tools with more than 2000 character descriptions. worth having a look at these

[desc_2000.csv](https://github.com/SSHOC/marketplace-curation/files/14929047/desc_2000.csv)

**Comment by mkrzmr** [comment]
Reviewed and fixed a few, most entries were ok
