### ISSUE TITLE
Keyword mapping

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/marketplace-curation#13]
for legacy issue and background information, see https://github.com/SSHOC/marketplace-curation/issues/1

**Comment by mkrzmr** [comment]
https://docs.google.com/spreadsheets/d/1-Oh9_SxIhfMAT6KNJrMf4LetCpy5s1fHZEyTL__TUVA/edit#gid=1862492073

**Comment by laureD19** [comment]
first classification collectively done with EB members with[ the following results ](https://docs.google.com/spreadsheets/d/1-Oh9_SxIhfMAT6KNJrMf4LetCpy5s1fHZEyTL__TUVA/edit#gid=883102613)

create a file format vocab and move this concept there | 32
delete | 62
duplicate (British vs. American English) | 23
keep it in keyword vocab | 1576
map to activity vocabulary | 73
Map to discipline vocabulary | 45
map to EOSC category | 5
map to invocation type | 1
map to language vocabulary | 145
map to standards | 16
merge | 124
move to contributors | 3
move to description | 1
Move to extent field | 29
relate to a SSHOMP item | 24
separate values | 89
typo | 29
Grand Total | 2277
