### ISSUE TITLE
add notebook identifying duplicated values in a given property

### ISSUE THREAD

**Issue by laureD19** [SSHOC/marketplace-curation#14]
MP production data have been cleaned from having duplicated values in the same property field.

Can you add your script to the dev branch @cesareconcordia , please?

**Comment by cesareconcordia** [comment]
@laureD19: [done](https://github.com/SSHOC/marketplace-curation/blob/dev/5.2CurationKeywords-Duplicates.ipynb), let me know in case of problems.
