### ISSUE TITLE
Add more item relations

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/marketplace-curation#30]
I made a simple script that searches all descriptions for names of tools already in the marketplace. So if a description mentions Textgrid, the tool will suggest a relation to it. The script only works on exact matches. 

This found 668 possible new relations we can add to the MP, but we should evaluate this approach first before we add the relations. 

Have a look at the spreadsheet here 
https://docs.google.com/spreadsheets/d/1ml2X_6_ZQJIfZYq-_GOeT91LAH7WJx3z1bpboDuliT4/edit#gid=360397178

And see if these suggested new relations make sense to you.

Next step can then be to create these relations through the API.

**Comment by mkrzmr** [comment]
- [x] add stopword list "project, origin, ..."
- [x] create relation through API

**Comment by laureD19** [comment]
32 relations created this morning on production
