### ISSUE TITLE
Curating URLs

### ISSUE THREAD

**Issue by dpancic** [SSHOC/marketplace-curation#6]
In GitLab by @laureD19 on Nov 23, 2022, 10:24

This is an umbrella issue to discuss URLs curation, especially the methods developed in the python library to flag broken URLs and the examples provided in [the related notebook](https://gitlab.gwdg.de/sshoc/marketplace-curation/-/blob/main/3.1CurationFlagURL.ipynb).

notify @KlausIllmayer @cesareconcordia @aureon249 @kreetrapper

**Comment by laureD19** [comment]
It works partially. After few more tests, it seems that the `datasets` category causes the error, but not the other categories. could you also try out on your side for datasets @cesareconcordia ? 

I wrote back to the MP for the other item categories. 11 new URL-flags raised to manually curate.

An additional question relates to the un-flagging of manually corrected items. From what you were explaining @cesareconcordia, I thought the `setHTTPStatusFlags` method would also unraise the URL-flag of items that have been manually corrected in the meantime, but it doesn't seem the case. Do I need to use another function?

notify also @aureon249

**Comment by cesareconcordia** [comment]
hi @laureD19: the problem you're having  checking URL for `dataset` items should be fixed now, please get the code from the repository and run the notebook, let me know if it still persists.

I'll check the behaviour of `setHTTPStatusFlags` to understand why it does not unraise URL-flags.

**Comment by aureon249** [comment]
Hi, I fetched the code from dev branch and ran the URL validity check (1.1) in the notebook for all five categories on stage. The error mentioned above did not reappear.

**Comment by laureD19** [comment]
Hi @cesareconcordia and @aureon249 !

I've tried out the URL checks and it now works with all categories. Thx!

Regarding the unflagging of items, my 2cts:
-  if it is supposed to be covered by the `setHTTPStatusFlags` then, we need to give another dataset as entry parameter than the df resulting from the URL checks as items to unflagged are not included in this result anymore. Seems to work, but need more tests.
- Another option could be to use `removePropertyFlag` before to set the flags again maybe, but I'm not sure I'm using it well. Are there some examples of use somewhere, @cesareconcordia ?
