### ISSUE TITLE
creating relations between tools and DH conf abstracts

### ISSUE THREAD

**Issue by laureD19** [SSHOC/marketplace-curation#7]
Pragmatical approach to create known relations between tools & publications based on the relations identified here: https://lehkost.github.io/tools-dh-proceedings/index.html

This should be done before deleting DHconf abstracts publications without any relations. 

Initial notebook: https://github.com/SSHOC/marketplace-curation/blob/dev/tools_publis_relations.ipynb 

notify also @cesareconcordia @KlausIllmayer @vronk

**Comment by laureD19** [comment]
[new version of the notebook ready](https://github.com/SSHOC/marketplace-curation/blob/dev/tools_publis_relations.ipynb), including the writing back of the relations to the MP (thanks @cesareconcordia !).

Tested on stage, ~500 relations created.
Ready to run on stage, estimation are 530 relations to create. 

Could someone (@cesareconcordia or @KlausIllmayer) have a look and give a green light so that I can run it on prod data?

**Comment by cesareconcordia** [comment]
Hi Laure, code is ok! @KlausIllmayer according to our informal standard procedure I would perform a database backup before running it on the production dataset.

**Comment by laureD19** [comment]
526 relations created this morning on production instance.
